### ISSUE TITLE
RemovePlayer methods don't work

### ISSUE THREAD

**Issue by derderdunichbist** [derderdunichbist/poker#12]
The `seatedPlayers` list contains all players on a table.
If we want to remove players from this list, should I

- call the ArrayList method `seatedPlayers.remove(int index)` or 

- set the value of the `seatedPlayers` list to null or

- set the seat values _(like name and seat number)_ to null ?

**Comment by SebastianZeeb** [comment]
In that case we should remove via index. The reason is that we keep iterating through the entire list, which makes no sense in the case that an index position is null. In other words : we remove that index, we don't have to test that position any further. 

It also helps avoiding nullpointers, which should not be occurring in the first place, but I'm just saying. We often iterate through seats and call methods such as show your hands etc., which all will throw exceptions if we do not remove the entire reference in our data structure / arraylist

**Comment by SebastianZeeb** [comment]
Also,  considering your other option (resetting attributes to null etc) : I don't particularly like this approach either simply because of the fact that we keep objects alive we are not using or interacting with. No harm in simply instantiating another object of seat as its needed.

**Comment by derderdunichbist** [comment]
Okay so another question is how do we select the next player? Because if we select the next player by the next index in the list, we have to add a certain player in the correct position to the list (remember that we specified that when a player leaves this seat becomes empty and the new player will added to this seat), am i right?
